### ISSUE TITLE
Could be more DRY

### ISSUE THREAD

**Issue by nynnejc** [mhtarokh/hyf-homework#1]
Is there a way to make this work with fewer lines? Look at how your fellow students solved it for clues!

https://github.com/mhtarokh/hyf-homework/blob/454eaea5338b08a4899ab844e4389614249b31ec/javascript/javascript1/week2/candyPrice.js#L36

**Comment by AdmWinther** [comment]
Do you mean lines 36-51? If yes, I should say those are lines for testing the code. I am not sure if I have understood you correctly! :-(

**Comment by nynnejc** [comment]
Thanks for the comment, I believe you did show me in class how you refactored code. I'm closing this issue.
