### ISSUE TITLE
JS2 Week 2 Feedback

### ISSUE THREAD

**Issue by orhantoy** [mhtarokh/hyf-homework#2]
@hosseinTa :v:

## Warm up exercises

- **Doubling of number:** ✅ Nice work! The style of the code could be a bit more readable by having consistent spacing but this is not a big deal for small scripts like this 👍 
  https://github.com/hosseinTa/hyf-homework/blob/b96474cc16cb889227eb83ff29600989990800ff/javascript/javascript2/week2/doubleOddNumbers/script.js#L1-L5
- **Working with movies/Exercise 1, 2, 3:** ✅  Nice work here as well
- **Working with movies/Exercise 4:** ✅ This works but this line https://github.com/hosseinTa/hyf-homework/blob/b96474cc16cb889227eb83ff29600989990800ff/javascript/javascript2/week2/movie/code.js#L15 actually does not copy the `movies` array. This means that in the `map` below when you set `movies.tag` it actually modifies the original objects in `movies`. The idea is that you should have done something like `const taggedMovies = movies.map(movie => { ... }` instead.
- **Working with movies/Exercise 5:** ✅ Nice and simple!
- **Working with movies/Exercise 6:** ✅ Looks good but the code is a bit hard to read. Instead I would've defined a new `const` and also split the `movies.title.includes()` checks per line.
- **Working with movies/Exercise 7:** ✅ This seems OK but can be a bit too complex and hard to fully understand.

## hyfBay

Nice work on this one as well 👍
`returnSearch` is perhaps not the most descriptive name here, something like `updateSearchResults` would be a bit better here.

---

I'll mark your assignment as approved ✅
Feel free to close this issue unless you have questions.

**Comment by chklueter** [comment]
Have you been seeing these comments @hosseinTa ? The issues you have are all still open so I'm checking if you even noticed ;)

**Comment by AdmWinther** [comment]
I tried to send a pull request including the updates from @orhantoy 's feedback. As @orhantoy said, they were not significant changes but I just wanted to give a pull request a try. So, I will appreciate if you check if I have done it correctly or not.
